server:
  port: 9290
  servlet:
    context-path: /corelayer-integrate

  tomcat:
    basedir: ./logs
    accesslog:
      enabled: true
      pattern: "%t %a %r %s (%D ms)"

spring:
  profiles:
    active: local

# elasticsearch集群名称，默认的是elasticsearch
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    hikari: #使用hikari连接池
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      pool-name: hikari
      register-mbeans: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000
